-   id: scriv
    name: scriv
    description: "Run 'scriv' the changelog management tool"
    entry: scriv create
    language: python
    'types_or': [python, pyi]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'